cli:
  auth_pass: admin
  authorize: true
  host: '{{ ansible_host }}'
  password: admin
  username: admin
hostname: OS10AWX-LEAF-3
os10_bgp:
  asn: 64626
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - admin: up
    adv_interval: 1
    fall_over: present
    ip: 30.10.1.4
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - admin: up
    adv_interval: 1
    fall_over: present
    ip: 30.10.2.4
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router_id: 10.0.2.3
os10_interface:
  ethernet 1/1/1:
    admin: up
  ethernet 1/1/10:
    admin: up
  ethernet 1/1/11:
    admin: up
  ethernet 1/1/12:
    admin: up
  ethernet 1/1/13:
    admin: up
  ethernet 1/1/14:
    admin: up
  ethernet 1/1/15:
    admin: up
  ethernet 1/1/16:
    admin: up
  ethernet 1/1/17:
    admin: up
  ethernet 1/1/18:
    admin: up
  ethernet 1/1/19:
    admin: up
  ethernet 1/1/2:
    admin: up
  ethernet 1/1/20:
    admin: up
  ethernet 1/1/21:
    admin: up
  ethernet 1/1/22:
    admin: up
  ethernet 1/1/23:
    admin: up
  ethernet 1/1/24:
    admin: up
  ethernet 1/1/25:
    admin: up
  ethernet 1/1/26:
    admin: up
  ethernet 1/1/27:
    admin: up
  ethernet 1/1/28:
    admin: up
  ethernet 1/1/29:
    admin: up
    desc: Uplink to OS10AWX-SPINE-2 1/1/3
    ip_and_mask: 30.10.2.5/31
    mtu: 9216
    switchport: false
  ethernet 1/1/3:
    admin: up
  ethernet 1/1/30:
    admin: up
    desc: Uplink to OS10AWX-SPINE-1 1/1/3
    ip_and_mask: 30.10.1.5/31
    mtu: 9216
    switchport: false
  ethernet 1/1/31:
    admin: up
    desc: VLT to OS10AWX-LEAF-4 1/1/31
    switchport: false
  ethernet 1/1/32:
    admin: up
    desc: VLT to OS10AWX-LEAF-4 1/1/32
    switchport: false
  ethernet 1/1/33:
    admin: up
  ethernet 1/1/34:
    admin: up
  ethernet 1/1/4:
    admin: up
  ethernet 1/1/5:
    admin: up
  ethernet 1/1/6:
    admin: up
  ethernet 1/1/7:
    admin: up
  ethernet 1/1/8:
    admin: up
  ethernet 1/1/9:
    admin: up
  loopback 0:
    admin: up
    ip_and_mask: 10.0.2.3/32
os10_lldp:
  enable: true
os10_prefix_list:
- entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 10.0.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 30.10.10.0
    number: 20
    permit: true
    state: present
  name: spine-leaf
  state: present
  type: ipv4
os10_route_map:
  route_map:
  - match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    name: spine-leaf
    permit: true
    seq_num: 10
os10_system:
  hostname: OS10AWX-LEAF-3
os10_vlt:
  discovery_intf: 1/1/31-1/1/32
  discovery_intf_state: present
  domain: 127
  peer_routing: true
  vlt_mac: 00:00:00:00:00:02
os10_xstp:
  enable: true
  intf: {}
  rstp:
    bridge_priority: 0
  type: rstp
